version: '3.7'

volumes:
  minio_data:

services:
  minio:
    image: minio/minio
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
    command: server /data
    environment:
      MINIO_ROOT_USER: test-access
      MINIO_ROOT_PASSWORD: test-secret
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3

  minio-client:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    environment:
      MC_HOST: 'minio=http://minio:minio123@minio:9000'
    entrypoint: /bin/sh
    command: -c '
      echo Waiting for Minio server to start... &&
      while ! mc alias set minio http://minio:9000 test-access test-secret; do sleep 1; done &&
      echo Connected to Minio server, creating bucket... &&
      mc mb minio/sdms-proof &&
      echo Bucket created.'