openapi: 3.0.3
info:
  title: projectwiki API
  version: '1.0'
  description: The projectwiki API
servers:
  - url: '/'
    description: Localhost

paths:
  /users/login:
    $ref: 'api/User.yml#/login'

  /test/test:
    $ref: 'api/Test.yml#/test'

components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://localhost:8082/realms/demo/protocol/openid-connect/auth
          scopes: {}

security:
  - OAuth2: []
