openapi: 3.0.3
info:
  title: projectwiki API
  version: '1.0'
  description: The projectwiki API
servers:
  - url: '/'
    description: Localhost

paths:
  /users/user:
    $ref: 'api/User.yml#/default'
  /users/user/search:
    $ref: 'api/User.yml#/search'
  /users/login:
    $ref: 'api/User.yml#/login'

  /test/test:
    $ref: 'api/Test.yml#/test'

components:
  parameters:
    TenantId:
      in: header
      name: X-Tenant
      required: true
      schema:
        type: string
      examples:
        Tenant 1:
          value: tenant1
        Tenant 2:
          value: tenant2
      x-ignore: true
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

security:
  - BasicAuth: []
